# Generated by Django 3.2.9 on 2021-11-25 15:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='profile_photo'),
        ),
    ]
