# Generated by Django 3.2.9 on 2021-11-25 15:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=''),
        ),
    ]
