# Generated by Django 3.2.9 on 2021-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
