# Generated by Django 3.2.9 on 2021-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211125_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiences',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='experiences',
            name='company',
            field=models.CharField(default='test company', max_length=250),
            preserve_default=False,
        ),
    ]
