# Generated by Django 3.2.9 on 2021-11-29 16:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20211128_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='image_path',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images'),
        ),
    ]
