# Generated by Django 3.2.9 on 2021-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211129_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv_path',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
