# Generated by Django 3.2.9 on 2021-12-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20211129_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='UISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('show', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
