# Generated by Django 3.2.9 on 2021-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_user_current_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
