# Generated by Django 3.2.9 on 2021-12-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20211209_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('short_desc', models.TextField()),
                ('main_desc', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, to='dashboard.Tags')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
