# Generated by Django 3.2.9 on 2021-12-14 13:08

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_blog_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_desc',
            field=django_quill.fields.QuillField(),
        ),
    ]
