# Generated by Django 3.2.9 on 2021-12-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_blog_main_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_desc',
            field=models.TextField(),
        ),
    ]
