# Generated by Django 3.2.9 on 2021-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_blog_main_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='dashboard.Tags'),
        ),
    ]
