# Generated by Django 3.2.9 on 2021-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_portfolios_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolios',
            options={'default_related_name': 'portfolios', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'default_related_name': 'tags', 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='dashboard.Tags'),
        ),
    ]
