# Generated by Django 3.2.9 on 2021-12-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20211216_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolios',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='dashboard.Tags'),
        ),
    ]
