# Generated by Django 4.0 on 2021-12-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20211216_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uisetting',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Blogtags', to='dashboard.Tags'),
        ),
    ]
