# Generated by Django 4.0 on 2021-12-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_uisetting_options_alter_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dashboard.Tags'),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dashboard.Tags'),
        ),
    ]
